### ISSUE TITLE
To-Do routing

### ISSUE THREAD

**Issue by itstechagain** [DebugBob/My_Dashboard#23]
# User Story

When I load my dashboard I can see my previously entered items on my list.

It is done when all the items I add to my list are saved and are available on login.

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added todo list functionality to the Dashboard component, including fetching todos from the server, displaying them, and allowing users to add new todos.

You can review changes in this commit: https://github.com/lkilu6456546/DebugBob-My_Dashboard-23/commit/2e4d697fa9b9f2105cb18c382b8417431964d74d.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
